//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_1_Overwatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hero
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hero()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public string HeroCode { get; set; }
        public string HeroName { get; set; }
        public string Category { get; set; }
        public string Image { get; set; }
        public string Strengths { get; set; }
        public string Weaknesses { get; set; }
        public string Counters { get; set; }
        public string Counteredby { get; set; }
        public string Synergy { get; set; }
        public string Discord { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
